# Generated by Django 2.1.1 on 2018-09-10 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentariosInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_recado', models.IntegerField(default='0')),
                ('apelido', models.CharField(default='', max_length=30, verbose_name='Apelido')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('status', models.CharField(choices=[('AP', 'Aprovado'), ('IN', 'Inativo'), ('RP', 'Reprovado')], default='IN', max_length=2, verbose_name='Status')),
                ('publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-publicacao',),
            },
        ),
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('cod_recado', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('apelido', models.CharField(default='', max_length=30, verbose_name='Apelido')),
                ('recado', models.TextField(verbose_name='Recado')),
                ('status', models.CharField(choices=[('AP', 'Aprovado'), ('IN', 'Inativo'), ('RP', 'Reprovado')], default='IN', max_length=2, verbose_name='Status')),
                ('publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-publicacao',),
            },
        ),
        migrations.AddField(
            model_name='comentariosinline',
            name='recado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Recado'),
        ),
    ]
