# Generated by Django 2.1.1 on 2018-09-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20180911_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariosinline',
            old_name='recado',
            new_name='recado_inline',
        ),
    ]
